# Import all crawler classes for direct use
from .fsc_crawler import FSC_Crawler
from .sfb_crawler import SFB_Crawler
from .central_bank__FX_crawler import CentralBankFX_Crawler
from .central_bank_crawler import CentralBank_Crawler
from .central_bank_law_crawler import CentralBankLaw_Crawler
from .twse_crawler import TWSE_Crawler
from .twse_dsp_crawler import TWSE_dsp_Crawler
from .twse_announcement_crawler import TWSE_announcement_Crawler
from .tpex_crawler import TPEx_Crawler
from .taifex_crawler import TAIFEX_Crawler
from .law_bank_crawler import LawBank_Crawler
from .twsa_crawler import TWSA_Crawler
from .tfutures_crawler import TFutures_Crawler
from .tdcc_crawler import TDCC_Crawler
from .moj_law_crawler import MOJ_Law_Crawler
from .gazette_crawler import GAZETTE_Crawler
from .banking_law_crawler import BankingLaw_Crawler
from .law_lib_crawler import Law_Lib_Crawler
from .trust_crawler import Trust_Crawler
from .selaw_crawler import SELAW_Crawler
